### ISSUE TITLE
Ouais, c'est stylé de sauter des évaluations nazes et tout, mais sinon Voltaire, c'est grave stylé à faire quand il n'y a pas la pression scolaire pour combler les lacunes de l'école défaillante. Le truc, c'est que c'est payant. À quand un fork du Projet Voltaire lui-même ?

### ISSUE THREAD

**Issue by bphd** [j0kr4/Automatic_projet_voltaire#1]

**Comment by j0kr4** [comment]
Grave stylé à faire ? Je ne suis pas aussi sûr. Quand ton école te dis de faire 72 heures sur projet voltaire sans prendre en compte les résultats. pourquoi vais-je me prendre la tête ? Un script qui fait passer les heures me suffit amplement. Je le partage pour éviter des galères à certains. Mais je ne me lancerais pas dans un fork de projet voltaire, à la fin de l'année j'en entendrais plus parler alors à quoi bon.

**Comment by bphd** [comment]
> Grave stylé à faire ? [...] Quand ton école te dis de faire 72 heures sur projet voltaire sans prendre en compte les résultats. pourquoi vais-je me prendre la tête ?

`c'est grave stylé à faire quand il n'y a pas la pression scolaire pour combler les lacunes de l'école défaillante`

> Un script qui fait passer les heures me suffit amplement. Je le partage pour éviter des galères à certains.

`Ouais, c'est stylé de sauter des évaluations nazes et tout`

> à quoi bon.

`c'est grave stylé à faire quand il n'y a pas la pression scolaire pour combler les lacunes de l'école défaillante`


Pour faire une troisième répétition reformulée, si tu veux, c'est claqué à cause du forçage de l'école, mais en soi comme outil, c'est vraiment le seul truc qui permet de prendre un niveau en français sans se faire chier. Tu te rends compte du truc des années après. Du coup, ça serait stylé de forker l'outil, surtout avec les algos d'apprentissage qui volent la data base, la partie dure est déjà faite. Avec le tableau faute/correction, il faut juste afficher la phrase avec la faute, puis donner le point si l'on a appuyé sur la faute ou pas, puis ensuite afficher la correction

**Comment by j0kr4** [comment]
Tu as l'air bien renseigné sur la façon de procéder. Tu n'as cas le faire ?
Je me répète mais cela ne me sert à rien personnellement, j'avais besoin de passer les heures de projet voltaire sans rester devant l'écran. C'est chose faite.
Je partage mon script et voila, je ne compte pas l'améliorer.
Si tu cherches un fork de projet voltaire ce ne sera pas ici.
